from Goals.class_education_goal import EducationGoal
from Goals.class_goal import Goal
from Goals.class_grow_wealth_goal import GrowWealthGoal
from Goals.class_income_goal import IncomeGoal, RetirementIncome
from Goals.class_real_estate_goal import RealEstateGoal
from Goals.class_retirement_goal import RetirementGoal
from Goals.class_savings_goal import SavingsGoal
from Goals.class_splurge_goal import SplurgeGoal
from Goals.class_startup_goal import StartupGoal
from Goals.class_travel_goal import TravelGoal
from Goals.class_wedding_goal import WeddingGoal